'use client'
import { AppSidebar } from "@/shared/components/app-sidebar";
import { ThemeModeToogle } from "@/shared/components/theme-mode-toogle";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/shared/ui/breadcrumb";
import { Separator } from "@/shared/ui/separator";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/shared/ui/sidebar";
import { Metadata } from "next";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";


// export const metadata: Metadata = {
//     title: "Перемещение",
//     description: "Generated by create next app",
//   };

export default function MovingLayout({ children }: Readonly<{ children: React.ReactNode }>) {

    const [breadcrumLink, setBreadcrumLink] = useState<string>('')
    const pathname = usePathname()
    console.log(pathname);
    const pathNames = pathname.split('/').splice(1, pathname.split('/').length - 1)
    console.log(pathNames);

    useEffect(() => {
        if (pathNames[0] === 'moving') {
            setBreadcrumLink('Перемещение')
        }
    }, [pathname])
    return (
        <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
                <header className="flex justify-between mr-5 h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                    <div className="flex items-center gap-2 px-4">
                        <SidebarTrigger className="-ml-1" />
                        <Separator orientation="vertical" className="mr-2 h-4" />
                        <Breadcrumb>
                            <BreadcrumbList>
                                <BreadcrumbItem className="hidden md:block">
                                    <BreadcrumbLink href="#">
                                        {breadcrumLink}
                                    </BreadcrumbLink>
                                </BreadcrumbItem>
                                <BreadcrumbSeparator className="hidden md:block" />
                                {/* <BreadcrumbItem>
                                    <BreadcrumbPage>{renderBreadcrumItem(pathNames[pathNames.length - 1])}</BreadcrumbPage>
                                </BreadcrumbItem> */}
                            </BreadcrumbList>
                        </Breadcrumb>
                    </div>
                    <ThemeModeToogle />
                </header>
                {children}
            </SidebarInset>
        </SidebarProvider>
    )
}